### ISSUE TITLE
CLI Shutdown / Restart 

### ISSUE THREAD

**Issue by phillipadsmith** [concierge/Kassy#179] opened 2016-06-29 23:03 UTC
@mrkno This may be totally obvious and I've just overlooked it... So, at the expense of asking a stupid question, how does one safely shutdown / restart Kassy from the CLI vs. through the `/restart` or `/shutdown` command sent from a platform? 

I ask about "safely" because bots might need to save data out to the `config.json` file for persistence. If I simply stop the node process, I don't believe this happens.

**Comment by mrkno** [comment] 2016-06-30 01:47
- `prefix + shutdown` (`/shutdown`/`!shutdown` usually) will invoke a safe shutdown.
- `prefix + restart` (`/restart`/`!restart` usually) will invoke a safe restart (shutdown safely then an almost complete hotswap of code).

Both of these will save data in the `exports.config` property for a module/integration, will call `exports.stop()` on an integration and will call `exports.unload()` on integrations/modules.

Invoking a safe shutdown from within a module itself will not be possible until the https://github.com/concierge/Kassy/pull/175 PR is merged. However it is currently possible inside an integration (call `exports.platform.shutdown()`).

**Comment by phillipadsmith** [comment] 2016-06-30 02:30
> It is worth noting that relatively recently I added a hook so that CTRL + C will so a safe shutdown inside the test integration. If there is no current test/shell like integration running it is not possible to invoke a safe shutdown from the CLI (which is why in general I would start with test as well as another integration, eg node main.js telegram test).

That's helpful. So, if I start with test, then I'll have access to use CTRL + C as a "safe shutdown" (saves config data). 

Is there a way to implement this same behaviour in other modules?

Phillip.

**Comment by phillipadsmith** [comment] 2016-06-30 04:01
> It is worth noting that relatively recently I added a hook so that CTRL + C will so a safe shutdown inside the test integration.

Hmmm... perhaps I'm not following here, @mrkno.

I'm starting with `node main.js telegram test` and when I CTRL + C the bot doesn't appear to "shutdown" in a way that saves any of the config data.

What am I missing?

**Comment by phillipadsmith** [comment] 2016-06-30 04:02
@mrkno Never mind, I missing the "recently I added a hook" part and I'm using an outdated version.  :-/

**Comment by mrkno** [comment] 2016-06-30 05:09
> Is there a way to implement this same behaviour in other modules?

As in, for example the telegram integration? Sure although if it is going to be implemented for those it should just be implemented for them all (in `platform.js` or some other part of the core code rather than a specific integration).

To intercept CTRL-C we would do something like the following:
```javascript
process.on('SIGINT', function() {
    platform.shutdown();
    process.exit();
});
```

**Comment by phillipadsmith** [comment] 2016-06-30 05:42
> although if it is going to be implemented for those it should just be implemented for them all (in platform.js or some other part of the core code rather than a specific integration).

Seems like a sensible thing to do, no?

The use case here is: 

* Script monitors the Kassy log file for common problems/errors, e.g., from the current Skype module
* Script restarts Kassy because a platform is not responding
* Shutdown should run so that persistence is, well, persistent

Any reason not to do this for all modules? 

Phillip.

**Comment by mrkno** [comment] 2016-06-30 05:58
Nope, no reason at all. I'll add it to my ever growing list of TODO's.

**Comment by mrkno** [comment] 2016-07-01 06:50
Resolved by https://github.com/concierge/Kassy/pull/175/commits/8ef295c866c73eadd9c9092e894b6ec42a3bec1a

**Comment by phillipadsmith** [comment] 2016-07-01 18:11
@mrkno I'm curious how you & other people using Kassy solve this pattern:

* Bot starts and is up-and-running on all platforms responding to commands
* At some point, usually just a few hours later, one of the platforms -- typically Skype, but not always -- stops working. So the bot is working on other platforms, but not all of the platforms that it was started with.

For a long-running bot / a bot that's supposed to be "up" not occasionally, but regularly, how do you currently handle this? 

Obviously, if I'm always interacting with the bot on all platforms -- which I'm not -- I could send the `restart` command. 

One can say: well, such-and-such, problem (the one that causes the error) will be fixed when X or Y happens. However, that doesn't account for the inevitability of platform problems, outages, etc.

So my work-around would be to monitory the log for typical problem patterns and issue a restart command, if I could do so programatically. But I'm wondering how others are managing this?

**Comment by mrkno** [comment] 2016-07-02 00:09
Typically the approach to this would be different instances (i.e. processes) per platform - at least this is what has been done for most other bots like hubot, etc. We just have the ability to deploy as one process for simplicity but with the simplification comes additional pain. In terms of stability of those platforms, the best approach is entirely over to the end user. Obviously there is no way of detecting a crash within Kassy itself easily (if it could detect its own crash it could restart easily but a crash usually kills any detection code anyway).

A sheduled restart would also help e.g. every 48hrs to 1 week. This would mean any failure by node to GC or the integration to maintain uptime would have reduced affect. As for an approach of detecting a crash other than monitoring the logs, I don't know. If you come up with a good way of detecting a problem and autorestarting an integration in code then a PR would be welcome.

The Skype problem is annoying and one I want to fix (even a hacked solution would be more acceptable than an outright crash). With the official bot API for skype the uptime is significantly better. In a similar way the MessengerBot API for facebook is a lot more stable (if less useful) than the unofficial facebook one.

If you absolutely need a stable bot I don't really have a suggestion for you. The problem is by no means unique to Kassy and fudemenatly Javascript is the wrong language for anything other than temporary or fun solutions.

**Comment by phillipadsmith** [comment] 2016-07-02 00:11
> fudemenatly Javascript is the wrong language for anything other than temporary or fun solutions.

Ha! Sacrilege! The gods of Node will rain terror upon the! ;-)

**Comment by phillipadsmith** [comment] 2016-07-02 00:14
> A sheduled restart would also help e.g. every 48hrs to 1 week.

More practically, how would it be possible to schedule a restart without a way to pass the process a SIGINT and have that result in a safe shutdown (where safe === persistent data saved)? Right now, if I kill the process, I lose any persistent data.

**Comment by mrkno** [comment] 2016-07-02 00:20
Some ways to do this:
- You mentioned you have a fork, you can pull in the commits I did yesterday (NZ time) which implement SIGINT
- A new core module could access `exports.platform.shutdown` on a `setTimeout`. Alternatively if you are thinking about the first solution you could also pull in the commits to make core and normal modules the same.
- Some hacky method to send the bot a `/restart` (or if you want to be really safe `/shutdown`)

**Comment by ParasDPain** [comment] 2016-07-02 01:57
How about running a separate process in `node` to monitor Kassy and restart as required? Here's (one of the many) [tools for the job](https://github.com/mafintosh/respawn)

Or if the node vm itself fails, perhaps we can write some restart-management in shell?

**Comment by phillipadsmith** [comment] 2016-07-09 20:25
@ParasDPain Respawn looks interesting. I'll give that a try. Many thanks. :-)

**Comment by mrkno** [comment] 2016-07-10 02:11
PR is now merged.

**Closed by mrkno** 2016-07-10 02:11 UTC
Labels: In PR, question
