### ISSUE TITLE
kpm installs linked to a raw coffee script fail to install

### ISSUE THREAD

**Issue by ParasDPain** [concierge/Kassy#167] opened 2016-06-08 11:30 UTC
`/kpm install xkcd` failed to install with the following message

```
fatal: repository 'https://raw.githubusercontent.com/github/hubot-scripts/master/src/scripts/xkcd.coffee/ ' not found
Cloning into '/tmp/tmp-4472Y2VPkienKvC8'...
fatal: repository 'https://raw.githubusercontent.com/github/hubot-scripts/master/src/scripts/xkcd.coffee/ ' not found
```

But was successfully installed when manually linking the script as

`/kpm install https://raw.githubusercontent.com/github/hubot-scripts/master/src/scripts/xkcd.coffee`

Possible cause is the `/` at the end of the link added by kpm

**Comment by mrkno** [comment] 2016-06-09 07:33
Can you verify that the intended behavior works before this is merged: https://github.com/concierge/Kassy/pull/169

**Comment by ParasDPain** [comment] 2016-06-09 13:31
Tested installs and uninstalls via `kpm` table and with links. Works fine as expected but one link did stuff it up

`/kpm install https://raw.githubusercontent.com/hubot-scripts/hubot-sentimental/master/src/sentimental.coffee`

with the following message

```
Loading module 'sentimental'... 
Error: Cannot find module 'Sentimental'
  at Function.Module._resolveFilename (module.js:339:15)
  at Function.Module._load (module.js:290:25)
  at Module.require (module.js:367:17)
  at require (internal/module.js:16:19)
  at Object.<anonymous> (/root/Dev/kassy_test/modules/kpm_sentimental/sentimental.coffee:21:11)
  at Object.<anonymous> (/root/Dev/kassy_test/modules/kpm_sentimental/sentimental.coffee:21:1)
  at Module._compile (module.js:413:34)
  at Object.loadFile (/root/Dev/kassy_test/node_modules/coffee-script/lib/coffee-script/register.js:16:19)
  at Module.load (/root/Dev/kassy_test/node_modules/coffee-script/lib/coffee-script/register.js:45:36)
  at Function.Module._load (module.js:314:12)
  at Module.require (module.js:367:17)
  at require (internal/module.js:16:19)
  at Object.exports.requireOrInstall (/root/Dev/kassy_test/core/install.js:42:12)
  at func (/root/Dev/kassy_test/core/require.js:20:21)
  at Function.func.once (/root/Dev/kassy_test/core/require.js:57:19)
  at Object.exports.loadModule (/root/Dev/kassy_test/core/modules/hubotModule.js:108:25)
  at Object.exports.loadModule (/root/Dev/kassy_test/core/modules/modules.js:37:45)
  at /root/Dev/kassy_test/core/core_modules/kpm.js:134:52
  at doneOne (/root/Dev/kassy_test/node_modules/fs-extra/lib/copy/ncp.js:237:40)
  at /root/Dev/kassy_test/node_modules/fs-extra/lib/copy/ncp.js:122:11
  at FSReqWrap.oncomplete (fs.js:82:15)
Loading Failed
Could not load module 'sentimental'. Does it have a syntax error?
Module "sentimental" could not be loaded.
```

**Comment by mrkno** [comment] 2016-06-11 05:29
@ParasDPain should be fixed as of https://github.com/concierge/Kassy/pull/169/commits/ad7e019d6f9ef154bcfe8ccc36fc7aab663ae5f2 (once again, could you check before merge).

**Note:** the `Sentimental` script requires a `redis` store to be setup and configured first (otherwise lots of errors) and does not play nice with shutdown.

**Comment by ParasDPain** [comment] 2016-06-13 07:14
@mrkno Tested `install` and `uninstall` features for all types of modules. Awesome work! Everything runs as expected :smile: 

Thanks for the pointers for `Sentimental` will keep that in mind :+1:

**Closed** 2016-06-14 04:27 UTC
Labels: bug, In PR
