### ISSUE TITLE
System config saving incorrectly

### ISSUE THREAD

**Issue by Awarua-** [concierge/Kassy#151] opened 2016-05-11 21:42 UTC
Some core intergrations config are gettings saved inside others,
Example:

```javascript
{
    "output": {
        "slack": {
            "name": "Kassy",
            "commandPrefix": "!",
            "grunt": {
                "commandPrefix": "/"
            },
            "skypebot": {
                "name": "Concierge",
                "commandPrefix": "!"
            }
        },
        "grunt": {
            "commandPrefix": "/"
        },
        "skypebot": {
            "name": "Concierge",
            "commandPrefix": "!"
        },
        "test": {
            "commandPrefix": "/",
            "threadId": 1,
            "senderId": 0,
            "senderName": "TESTING",
            "commandHistory": [
                "/update",
                "/update",
                "/update",
                "/update",
                "/restart",
                "/restart",
                "/update",
                "/ping"
            ],
            "grunt": {
                "commandPrefix": "/"
            },
            "skypebot": {
                "name": "Concierge",
                "commandPrefix": "!"
            }
        },
        "facebook": {
            "testingName": "edoctest",
            "commandPrefix": "!"
        },
        "skype": {
            "commandPrefix": "!"
        }
    },
    "disabled": {},
    "update": {
        "autoUpdateEnabled": true,
        "autoUpdatePeriod": 100000000
    }
}
```

**Comment by mrkno** [comment] 2016-05-12 05:12
Given this bug was already fixed recently, technically its a regression.

**Comment by Awarua-** [comment] 2016-05-18 00:26
May only be an issue, with my development environment, anyone else able to reproduce?

**Comment by mrkno** [comment] 2016-05-18 05:37
Easy to reproduce: Create a new integration section in `config.json:output` for an integration module that doesn't exist.

The behaviour in that case is by design - copying old style config into each of the new style config sections. This code can probably be removed now anyway cause noone should have these sections anymore.

**Comment by mrkno** [comment] 2016-06-12 01:59
Whether this bug exists or not, it will be permanently resolved by https://github.com/concierge/Kassy/commit/9a372371ed8c50fe1f71aae65b20add2606f5573

**Closed by mrkno** 2016-06-12 01:59 UTC
Labels: bug, regression
